name: 'Build'

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout codebase'
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build -L
